/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bankcomm.embs;

import java.lang.Thread;

public class App {
    public String getGreeting() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                int count = 0;
                while(true) {
                    System.out.println("here!!! " + count);
                    count++;
                    try{
                        Thread.sleep(1000);
                    }catch(Exception e) {

                    }                 
                }
                
            }
        }).start();
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        while(true) {
            try{
                Thread.sleep(1000);
            }catch(Exception e){

            }
            
        }
    }
}
